FROM node:16-alpine

LABEL app="alura_nest"

RUN apk add --update --no-cache \
  bash \
  curl \
  git

WORKDIR /home/node/app

RUN yarn global add @nestjs/cli

COPY package.json .

RUN yarn install --silent

COPY . .

RUN yarn build

ENTRYPOINT [ "yarn", "start:prod" ]

USER node

EXPOSE 3000